dpi = 300
inner_margin = 1
resize = false
# frontside_only: print only the front side of the badge. Everything related to
# the backside is ignored.
frontside_only = false
# double_sided: write text on both sides
double_sided = true

[page]
height = 297
width = 210

[badge]
height = 147
width = 104

[name]
height = 24.5
width = 93.6
vertical_offset = 66
font_name = "DejaVuSans.ttf"
font_size = 256
color = "0x000000"

[lastname]
height = 21
width = 93.6
vertical_offset = 88
# vertical_offset_if_null: if lastname is empty apply this offset to
#   group.vertical_offset
vertical_offset_if_null = -5
font_name = "DejaVuSans.ttf"
font_size = 172
color = "0x000000"

[group]
height = 18
width = 93.6
vertical_offset = 105
font_name = "DejaVuSans.ttf"
font_size = 136
color = "0x000000"

[logo]
height = 18
width = 93.6
vertical_offset = 105
